### ISSUE TITLE
Broken link to "Writing Great Documentation"

### ISSUE THREAD

**Issue by bzums** [matheusfelipeog/beautiful-docs#142]
The following link is broken https://jacobian.org/writing/great-documentation/ and I cannot find the article anywhere.

**Comment by johnmachan** [comment]
Seems to work now.

**Comment by iamwilhelm** [comment]
It's broken now that Jacobian changed the design of his website.

**Comment by iamwilhelm** [comment]
He fixed it.

https://twitter.com/jacobian/status/1067499344620855297

**Comment by EABrown3** [comment]
Dead link: http://blog.parse.com/learn/engineering/designing-great-api-docs/ 
Cannot find the title in the 'learn' tagged items.

**Comment by matheusfelipeog** [comment]
> Dead link: http://blog.parse.com/learn/engineering/designing-great-api-docs/ Cannot find the title in the 'learn' tagged items.

@EABrown3 I updated the link to a site where the original text of the post still exists. See the commit: https://github.com/matheusfelipeog/beautiful-docs/commit/3f875c595eef552c5dfbda253fc0925ea57569e2

Thank you very much for informing.

**Comment by matheusfelipeog** [comment]
> The following link is broken https://jacobian.org/writing/great-documentation/ and I cannot find the article anywhere.

@bzums It seems to work now, but I updated the link anyway. See the commit: https://github.com/matheusfelipeog/beautiful-docs/commit/0312447c3da527a6eabf92671b73acb54f0dbebe

Thank you so much for opening this issue and letting me know ;)
