### ISSUE TITLE
Dead since early 2017 - no PR merges, issues responded to. Add: docz, docusaurus

### ISSUE THREAD

**Issue by estaub** [matheusfelipeog/beautiful-docs#156]
I was going to do a PR on docz and docusaurus, but it's clearly pointless.

**Comment by mikbeach** [comment]
I was also looking to do a PR, maybe it's time for a fork

**Comment by PharkMillups** [comment]
Hi. Sorry. I've been quite bad about this repo. Anyone interested in taking it over?

**Comment by mikbeach** [comment]
I'm interested, been looking at putting something similar together myself with an eye on helping imporove the docs on the Design System im working on [@sainsburys-tech](https://github.com/sainsburys-tech/)

**Comment by PharkMillups** [comment]
Nice. Happy to hand if off if you'll be able to whip it into shape and give it a nice home. Shoot me an email - mark@helium.com - and we'll get it sorted.

**Comment by King-of-Spades** [comment]
Not sure if resurrecting this took off, though I thought I'd do some updates on a fork on a whim: https://github.com/King-of-Spades/beautiful-docs-reborn

Happy to collab :D

**Comment by matheusfelipeog** [comment]
Guys, beautiful-docs is alive again 🚀 

PharkMillups transferred ownership of this project to me. Soon I will resolve all issues and PRs.
